### ISSUE TITLE
Image reference lookup fails when using an image uploaded by tenant

### ISSUE THREAD

**Issue by jistr** [os-migrate/os-migrate#346]
Reported in https://github.com/os-migrate/os-migrate/issues/343#issuecomment-765321050 . Glance API/SDK doesn't support filtering for `find_image()`. We will have to use a non-standard query, probably via `images()` (a list method) and pick the image from there.

`Traceback (most recent call last): File "/root/.ansible/tmp/ansible-tmp-1611312159.7801816-862119-48005581818750/AnsiballZ_import_workload_create_instance.py", line 102, in <module> _ansiballz_main() File "/root/.ansible/tmp/ansible-tmp-1611312159.7801816-862119-48005581818750/AnsiballZ_import_workload_create_instance.py", line 94, in _ansiballz_main invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS) File "/root/.ansible/tmp/ansible-tmp-1611312159.7801816-862119-48005581818750/AnsiballZ_import_workload_create_instance.py", line 40, in invoke_module runpy.run_module(mod_name='ansible_collections.os_migrate.os_migrate.plugins.modules.import_workload_create_instance', init_globals=None, run_name='__main__', alter_sys=True) File "/usr/lib64/python3.6/runpy.py", line 205, in run_module return _run_module_code(code, init_globals, run_name, mod_spec) File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code mod_name, mod_spec, pkg_name, script_name) File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_create_instance.py", line 255, in <module> File "/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_create_instance.py", line 251, in main File "/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_create_instance.py", line 241, in run_module File "/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/module_utils/server.py", line 76, in create File "/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/module_utils/server.py", line 86, in sdk_params File "/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/module_utils/server.py", line 197, in _refs_from_ser File "/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/module_utils/reference.py", line 17, in image_id File "/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/module_utils/reference.py", line 305, in _fetch_id TypeError: find_image() got an unexpected keyword argument 'project_id' fatal: [localhost]: FAILED! => { "changed": false, "module_stderr": "Traceback (most recent call last):\n File \"/root/.ansible/tmp/ansible-tmp-1611312159.7801816-862119-48005581818750/AnsiballZ_import_workload_create_instance.py\", line 102, in <module>\n _ansiballz_main()\n File \"/root/.ansible/tmp/ansible-tmp-1611312159.7801816-862119-48005581818750/AnsiballZ_import_workload_create_instance.py\", line 94, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File \"/root/.ansible/tmp/ansible-tmp-1611312159.7801816-862119-48005581818750/AnsiballZ_import_workload_create_instance.py\", line 40, in invoke_module\n runpy.run_module(mod_name='ansible_collections.os_migrate.os_migrate.plugins.modules.import_workload_create_instance', init_globals=None, run_name='__main__', alter_sys=True)\n File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n return _run_module_code(code, init_globals, run_name, mod_spec)\n File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n mod_name, mod_spec, pkg_name, script_name)\n File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n exec(code, run_globals)\n File \"/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_create_instance.py\", line 255, in <module>\n File \"/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_create_instance.py\", line 251, in main\n File \"/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_create_instance.py\", line 241, in run_module\n File \"/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/module_utils/server.py\", line 76, in create\n File \"/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/module_utils/server.py\", line 86, in sdk_params\n File \"/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/module_utils/server.py\", line 197, in _refs_from_ser\n File \"/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/module_utils/reference.py\", line 17, in image_id\n File \"/tmp/ansible_os_migrate.os_migrate.import_workload_create_instance_payload_xsk2q5op/ansible_os_migrate.os_migrate.import_workload_create_instance_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/module_utils/reference.py\", line 305, in _fetch_id\nTypeError: find_image() got an unexpected keyword argument 'project_id'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1 } `

**Comment by jistr** [comment]
Workaround: edit `workloads.yml` and set domain name and project name to null in image_ref:

```
   image_ref:
      domain_name: null
      name: some_image_name
      project_name: null
```
